sudo: required
services: 
  - docker

before_install: 
  - docker build -t jesimage -f Dockerfile.dev .

script: 
  - docker run -e CI=true jesimage npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: DockerReact
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-947838407953"
  bucket_path: "DockerReact"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY